### ISSUE TITLE
Soft-Locked

### ISSUE THREAD

**Issue by vsdfff** [Skittyblock/SixLS#34] opened 2024-02-26 12:15 UTC
The Disable home button Function and the non-iOS 6 lockscreen bug happend making my iphone soft-locked forever the only apps that can open is a camera app only

**Comment by vsdfff** [comment] 2024-02-26 12:16
iphone 7 plus ios 15.8 palera1n rootless

**Comment by Skittyblock** [comment] 2024-03-02 02:37
Just a duplicate of #8. You can reboot and then jailbreak with tweak injection disabled to install, or reset settings via ssh.

**Closed as not planned by Skittyblock** 2024-03-02 02:37 UTC
Labels: duplicate
